version: '2'
services:

    nginxWeb:
        restart: always
        image: nginx
        volumes:
         - nginxConf:/etc/nginx/conf.d
         - ngincVhosts:/etc/nginx/vhost.d
         - nginxHtml:/usr/share/nginx/html
         - nginxCerts:/etc/nginx/certs:ro
        ports:
         - "80:80"
         - "443:443"
         
    nginxGen:
        restart: always
        image: jwilder/docker-gen
        volumes_from:
         - nginxWeb
        volumes:
         - /home/ubuntu/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
         - /var/run/docker.sock:/tmp/docker.sock:ro
        command: |
            -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf


    nginxLetsencrypt:
        restart: always
        environment:
            NGINX_DOCKER_GEN_CONTAINER: ranchercompose_nginxGen_1
        volumes_from:
         - nginxWeb
        volumes:
         - nginxCerts:/etc/nginx/certs:rw
         - /var/run/docker.sock:/var/run/docker.sock:ro
        image: jrcs/letsencrypt-nginx-proxy-companion
    
    rancherServer:
        restart: always
        environment:
            CATTLE_DB_CATTLE_MYSQL_HOST: mysqldb
            CATTLE_DB_CATTLE_MYSQL_PORT: 3306
            CATTLE_DB_CATTLE_MYSQL_NAME: cattle
            CATTLE_DB_CATTLE_USERNAME: cattle
            CATTLE_DB_CATTLE_PASSWORD: password
            VIRTUAL_HOST: rancher.opensaas.local
            VIRTUAL_PORT: 8080
            LETSENCRYPT_HOST: rancher.opensaas.local
            LETSENCRYPT_EMAIL: example@example.com
        image: rancher/server

    mysqldb:
        restart: always
        environment:
            MYSQL_PASSWORD: password
            MYSQL_USERNAME: cattle
            MYSQL_DATABASE: cattle
            MYSQL_ROOT_PASSWORD: password
        image: mysql
        volumes:
         - rancherMysqlData:/var/lib/mysql