db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: edxapp
        MYSQL_USER: edxapp001
        MYSQL_PASSWORD: password
    volumes:
     - ${EDX_MYSQL_DATA_ROOT}:/var/lib/mysql
    volume_driver: ${volume_driver}

mongo:
    labels:
        io.rancher.sidekicks: mongoConfig
    image: mongo:3.3
    volumes:
     - ${EDX_MONGO_DATA_ROOT}:/data/db
    volume_driver: ${volume_driver}

mongoConfig:
    image: mongo:3.3
    labels:
        io.rancher.container.hostname_override: container_name
        io.rancher.container.start_once: true
    command: |
      bash -c "echo 'db.createUser({ user: \"edxapp\", pwd: \"password\", roles: [ { role: \"readWrite\", db: \"edxapp\" } ] });' > createEdxappUser.js; mongo mongo/edxapp createEdxappUser.js"
    
# Need to build our own for ES 0.9
es:
    image: opensaas/edx-elasticsearch
    volumes:
     - ${EDX_ES_DATA_ROOT}:/data
    volume_driver: ${volume_driver}

memcache:
    image: memcached:1.4.24
    volumes:
     - ${EDX_MEMCACHE_DATA_ROOT}:/data
    volume_driver: ${volume_driver}


rabbitmq:
    image: rabbitmq:3.5.3
    volumes:
     - ${EDX_RABBIT_DATA_ROOT}:/var/lib/rabbitmq
    volume_driver: ${volume_driver}

forums:
    container_name: forums
    image: edxops/forums:opencraft-v2
    volumes:
     - ${EDXAPP_CS_COMMENTS_ROOT}:/edx/app/forum/cs_comments_service
    volume_driver: ${volume_driver}
   

lms:
    labels:
        io.rancher.container.pull_image: always
        io.rancher.sidekicks: edxappConfig
    image: opensaas/edxapp
    volumes:
     - ${EDXAPP_PLATFORM_ROOT}:/edx/app/edxapp
     - /dev/log:/dev/log
    volume_driver: ${volume_driver}

cms:
    labels:
        io.rancher.container.pull_image: always
    image: opensaas/edxapp
    volumes:
     - ${EDXAPP_PLATFORM_ROOT}:/edx/app/edxapp
     - /dev/log:/dev/log
    volume_driver: ${volume_driver}

edxappConfig:
    image: opensaas/edxapp
    volumes:
     - ${EDXAPP_PLATFORM_ROOT}:/edx/app/edxapp
     - /dev/log:/dev/log
    labels:
        io.rancher.container.hostname_override: container_name
        io.rancher.container.start_once: true
    volume_driver: ${volume_driver}
    command: bash -c "cd /edx/app/edx_ansible/edx_ansible/docker/plays; /edx/app/edx_ansible/venvs/edx_ansible/bin/ansible-playbook edxapp.yml -i '127.0.0.1,' -c local -t 'install:base,install:configuration,install:app-requirements,install:code' -e@/ansible_overrides.yml; sudo su edxapp -s /bin/bash; source edxapp/edxapp_env; python /edx/app/edxapp/edx-platform/manage.py cms syncdb --settings=aws"