db:
    image: mysql:5.7
    labels:
        io.rancher.sidekicks: dbConfig
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: edxapp
        MYSQL_USER: edxapp001
        MYSQL_PASSWORD: password
    volumes:
     - ${EDX_MYSQL_DATA_ROOT}:/var/lib/mysql
    volume_driver: ${volume_driver}
    
dbConfig:
    image: mysql:5.7
    labels:
        io.rancher.container.hostname_override: container_name
        io.rancher.container.start_once: true
    command: |
      bash -c "sleep 2m; mysql -uroot -ppassword -h db -e \"create database edxapp_csmh;\""

mongo:
    labels:
        io.rancher.sidekicks: mongoConfig
    image: mongo:3.3
    volumes:
     - ${EDX_MONGO_DATA_ROOT}:/data/db
    volume_driver: ${volume_driver}

mongoConfig:
    image: mongo:3.3
    labels:
        io.rancher.container.hostname_override: container_name
        io.rancher.container.start_once: true
    command: |
      bash -c "sleep 2m; echo 'db.createUser({ user: \"edxapp\", pwd: \"password\", roles: [ { role: \"readWrite\", db: \"edxapp\" } ] });' > createEdxappUser.js; mongo mongo/edxapp createEdxappUser.js"
    
# Need to build our own for ES 0.9
#es:
#    image: opensaas/edx-elasticsearch
#    volumes:
#     - ${EDX_ES_DATA_ROOT}:/data
#    volume_driver: ${volume_driver}

memcache:
    image: memcached:1.4.24
    volumes:
     - ${EDX_MEMCACHE_DATA_ROOT}:/data
    volume_driver: ${volume_driver}


#rabbitmq:
#    image: rabbitmq:3.5.3
#    volumes:
#     - ${EDX_RABBIT_DATA_ROOT}:/var/lib/rabbitmq
#    volume_driver: ${volume_driver}

#forums:
#    container_name: forums
#    image: edxops/forums:opencraft-v2
#    volumes:
#     - ${EDXAPP_CS_COMMENTS_ROOT}:/edx/app/forum/cs_comments_service
#    volume_driver: ${volume_driver}
   

edxapp:
    labels:
        io.rancher.container.pull_image: always
    image: opensaas/edxapp
    volumes:
     - ${EDXAPP_PLATFORM_ROOT}:/edx/app/edxapp
     - /dev/log:/dev/log
    volume_driver: ${volume_driver}


edxappConfig:
    image: opensaas/edxapp
    volumes:
     - ${EDXAPP_PLATFORM_ROOT}:/edx/app/edxapp
     - /dev/log:/dev/log
    labels:
        io.rancher.container.hostname_override: container_name
        io.rancher.container.start_once: true
    volume_driver: ${volume_driver}
    command: |
        bash -c "sleep 5m; rm -rf /edx/app/edx_ansible/edx_ansible; git clone https://github.com/OpenSaasAU/edx-configuration /edx/app/edx_ansible/edx_ansible; cd /edx/app/edx_ansible/edx_ansible/docker/plays; /edx/app/edx_ansible/venvs/edx_ansible/bin/ansible-playbook edxapp.yml -i '127.0.0.1,' -c local -e \"EDXAPP_PYTHON_SANDBOX=false edxapp_cms_gunicorn_host=0.0.0.0 edxapp_lms_gunicorn_host=0.0.0.0 migrate_db='yes' COMMON_MYSQL_MIGRATE_USER='root' edxapp_staticfile_dir='/edx/app/staticfiles'\" -t 'install:base,install:configuration,install:app-requirements,install:code,deploy,gather_static_assets,migrate' -e@/ansible_overrides.yml; source /edx/app/edxapp/edxapp_env"