db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: edxapp
        MYSQL_USER: edxapp001
        MYSQL_PASSWORD: password
    volumes:
     - ${EDX_MYSQL_DATA_ROOT}:/var/lib/mysql
    volume_driver: ${volume_driver}

mongo:
    image: mongo:3.3
    volumes:
     - ${EDX_MONGO_DATA_ROOT}:/data/db
    command: "--auth"
    volume_driver: ${volume_driver}


# Need to build our own for ES 0.9
es:
    image: opensaas/edx-elasticsearch
    volumes:
     - ${EDX_ES_DATA_ROOT}:/data
    volume_driver: ${volume_driver}

memcache:
    image: memcached:1.4.24
    volumes:
     - ${EDX_MEMCACHE_DATA_ROOT}:/data
    volume_driver: ${volume_driver}

nginx:
    image: opensaas/edx-nginx

rabbitmq:
    image: rabbitmq:3.5.3
    volumes:
     - ${EDX_RABBIT_DATA_ROOT}:/var/lib/rabbitmq
    volume_driver: ${volume_driver}

forums:
    container_name: forums
    image: edxops/forums:opencraft-v2
    volumes:
     - ${EDXAPP_CS_COMMENTS_ROOT}:/edx/app/forum/cs_comments_service
    volume_driver: ${volume_driver}
   
   
xqueue:
    image: opensaas/edx-xqueue
    volumes:
     - ${EDXAPP_XQUEUE_ROOT}:/edx/app/edxapp/xqueue
    volume_driver: ${volume_driver}

lms:
    image: opensaas/edxapp
    volumes:
     - ${EDXAPP_PLATFORM_ROOT}:/edx/app/edxapp/edx-platform
     - /dev/log:/dev/log
    volume_driver: ${volume_driver}

cms:
    image: opensaas/edxapp
    volumes:
     - ${EDXAPP_PLATFORM_ROOT}:/edx/app/edxapp/edx-platform
     - /dev/log:/dev/log
    volume_driver: ${volume_driver}
